### ISSUE TITLE
Incorrect sprites displayed

### ISSUE THREAD

**Issue by zsotroav** [itsjavi/livingdex#11]
Red core (uses meteor form, which is unavailable in HOME)
Yellow core and (uses violet)
Violet core (uses red)
are not displayed using the correct sprites

**Comment by zsotroav** [comment]
Silvally also uses an incorrect form's sprite.
Hoopa and Hoopa Unbound are switched.
Pumpkaboo, Oricorio, and Furfrou has mixed up sprites

**Comment by itsjavi** [comment]
thanks for reporting, there is some bug in the spritesheet generator in the way forms are sorted.
will fix soon

**Comment by itsjavi** [comment]
fixed
