### ISSUE TITLE
Feedback on sorting modes

### ISSUE THREAD

**Issue by gvieralopez** [itsjavi/livingdex#12]
Dear Javier,

First, I want to say thanks for your dedication and great work. This project is exactly what every collector needs to help her (or him) sort HOME boxes.

I tried to reach you in the discord server but the invite didn't worked. I have a few suggestions regarding the sorting:

1. You could add also 2 boxes dedicated to Gigamax forms, even when they look the same in the thumbnails, having them unlocks entries in the pokedex and they can be considered important parts of a living dex.
2. While in 'Boxes Grouped' the box called 'Gen 7 Forms' has a 'Rockruff' that I cannot understand why it is there. I cannot spot any differences with the one on the regular box of the main pokedex. There is also a Rockruff in the box of 'Special Ability Forms', but that is clear to me.
3. Even when I love the 'Boxes Grouped' mode (It is indeed what I am following), I recommend you to add something like a 'Boxes Grouped Minimal' that doesn't involve the collector to have duplicates of very rare mythical species since those are the hardest to find. A good example of this kind of sorting can be found here: https://www.serebii.net/pokemonhome/depositablepokemon-sorted.shtml

Overall, I really like your project and sorting you proposed. If you provide some help to run it locally I could try to make a PR with the changes. Thank you in advance.

**Comment by itsjavi** [comment]
hey thank you, note taken! actually I also thought about having a gmax box going to push it this weekend

**Comment by itsjavi** [comment]
Closing, all of this is currently being implemented in the [new living dex site](https://supereffective.gg/apps/livingdex)

About the duplicated rockruff, it's just that visually is nice to see all the forms  and evolution line together, but you are righ about the rare legendary/mythical duplicates.
