### ISSUE TITLE
Missing forms of Zygarde, Rockruff and Greninja?

### ISSUE THREAD

**Issue by timbru31** [itsjavi/livingdex#2]
Hi 👋,

this is an awesome and really promising project, I like the visual approach instead of kilometer long spreadsheets.
However, I've noticed some differences in comparison with other lists:

1. Ash-Greninja (#658) can be registered with Pokémon Home and the regular form has two abilities, making it actually three entries in the National Dex:
    1. > The 3 forms are "regular", "regular with ability battle bond" and "battle bond form" (https://www.reddit.com/r/PokemonHome/comments/hf1pat/does_anyone_know_whats_the_3rd_form_of_greninja/fvus90b/)
2. The complete form of Zygarde (#718) seems missing, too.
    1. Further sources even say that both 10% and 50% with Power Construct as well as 10% and 50% with Aura Break count individually, making it 5 Zygrade entries in the National Dex.
3. Home lists two entries for Rockruff (#744), because only the "Own Tempo" ability evolves into Lycanroc Dusk Form

It would be awesome if your list could be updated to reflect those changes/missing entries 💯

**Comment by itsjavi** [comment]
Hey thanks for the feedback, for some reason I missed the notifications regarding the open issues of this project.
Basically what you suggest is that Pokémon with special abilities count as an individual form and take a space in the living dex.

I think it makes sense. 
Probably it will come with the next wave of features I want to add (more info on click, filters, checklists, shinies, etc.).

**Comment by itsjavi** [comment]
Good news, this has been implemented in the new version.
