### ISSUE TITLE
Issue with genders

### ISSUE THREAD

**Issue by ProfAspen** [itsjavi/livingdex#4]
Unless I could not find it, it seems the female pikachu is missing while all the hat ones are there? I was thinking the gigantimax was a female but it doesnt seem so? This is a great project. Ive put lots of work into a spreadsheet i have with all forms like this, except i can track whos in what ball and from what game.

**Comment by ProfAspen** [comment]
Found it

**Comment by itsjavi** [comment]
>  i can track whos in what ball and from what game.
this is a good idea.
