### ISSUE TITLE
Furfrou forms 

### ISSUE THREAD

**Issue by zsotroav** [itsjavi/livingdex#9]
Hi, thanks for the awesome tool and for keeping it clean! However, Furfrou forms are now completely available in HOME and are missing from the list.

Missing forms:
* Heart Trim 
* Star Trim 
* Diamond Trim 
* Debutante Trim
* Matron Trim 
* Dandy Trim 
* La Reine Trim 
* Kabuki Trim
* Pharaoh Trim

**Comment by itsjavi** [comment]
thanks, it has been added now
